### ISSUE TITLE
Fix and refactor

### ISSUE THREAD

**Issue by GitMatt101** [GitMatt101/CGO#8]
This issue collects a variety of problems that need to be fixed.

There are some warnings laying around, would be better if they got fixed.
Some code sections can be improved, below a list of what needs to be done:
- [x] In mutable states remove '.value' and use 'by' in the declaration
- [x] Replace PreferencesManager with datastore - Fixed in #20 
- [x] Replace Divider with HorizontalDivider in RegistrationScreen - Fixed in #45 
- [x] Replace user email with user id in navigation - Fixed in #20 
- [x] Change text on empty match history in user profile - Fixed in #29 
- [x] Change profile match history to see only the games that the user played - Fixed in #29 
- [x] Fix arrow back button after registration - Fixed in #45 
- [x] Add the time picker and location picker in the AddEventScreen - Added in #26
- [x] Remove Scaffolds to avoid automatic padding - Fixed in #38 
- [x] Put every repeated composable in the composables folder - Fixed in #38 
- [x] Add check for maximum participants - Fixed in #36 
- [x] Fix flickering in rankings screen - Fixed in #40 
- [x] Add scrollable to all screens that need it - Added in #55 
- [x] Fix games won - Fixed in #43 
- [x] Add constraints when adding the event - Fixed in #47
- [x] Improve the map - Fixed in #49
- [x] Add login check in all screens that need it - Fixed in #55
